# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.0.0
group=com.cursee.specter
java_version=17

# Common
mod_id=specter
mod_name=Specter
mod_author=Jason13
license=Unlicense
credits=Thanks to Jaredlll08, Darkhax-Minecraft, Serilum, and PacifistMC
description=Inspired by Ghosts from Destiny (2014).

# Minecraft
minecraft_version=1.20.1
minecraft_version_range=[1.20.1, 1.20.2)

# ParchmentMC, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.92.6+1.20.1
fabric_loader_version=0.16.9

# Forge, see https://files.minecraftforge.net/net/minecraftforge/forge/index_1.20.1.html for new versions
forge_version=47.4.10
forge_loader_version_range=[46,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
